// import Head from "next/head";
// import localFont from "next/font/local";
// // import Image from "next/image";
// import Script from "next/script";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
     
        
//   {/* <video className="absolute inset-0 w-full h-full  object-cover "  autoPlay muted loop>
//     <source src="/aivideo2.mp4" type="video/mp4" />
//   </video> */}
  
  




//   <video classname="background-video pb-6" autoPlay muted loop>
//     <source src="/1019.mp4" type="video/mp4" />
//   </video>
//   <div className="m-auto flex justify-center mb-28">
//   <div classname="content ">

//     {/* <!-- Your content here --> */}
//     <img src='Logo.gif' classname=" h-60 w-50 m-auto" />
// <h1 className="text-center font-bold text-4xl ">Shakktii AI</h1>
// <div className="container">    <span classname=" text-xl font-semibold text-center animated-text"></span>
// </div> {/* <p classname="mt-4 text-xl text-center">EXPLORE UNLIMITED STRENGTH OF</p> */}
//     {/* <p classname="mt-4 text-xl text-center">AI</p> */}
    
//   </div></div>
//   <Script 
//         src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js" 
//         strategy="afterInteractive" 
//         onLoad={() => {
//           new Typed('.animated-text', {
//             strings: ['EXPLORE UNLIMITED STRENGTH', 'WITH ARTIFOCIAL INTELLIGENCE'],
//             typeSpeed: 50,
//             backSpeed:60,
//             backDelay:1000,
//             loop:true,

//           });
//         }} 
//       />
// </>
//   );
// }


import Head from "next/head";
import localFont from "next/font/local";
import Script from "next/script";

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img id="Home" className="background-video desktop "src="/ai1.jpg"   />
      <img id="HomeMobile" class="background-video mobile" src="/ai2.jpg" />
        {/* <source src="/1019.mp4" type="video/mp4" /> */}
      {/* </video> */}
   



      <div className="m-auto flex justify-center mb-28">
        <div className="content"><div className="main">
          <img src="/Logo.gif" alt="Logo" className="h-60  w-auto m-auto logo" /></div>
          <h1 className="text-center mt-5 font-bold text-4xl h1">Shakktii AI</h1>
          <div className="container mb-10">
            <span className="text-xl font-semibold text-center animated-text"></span>
          </div>
        </div>
      </div>

      <Script
        src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"
        strategy="afterInteractive"
        onLoad={() => {
          new Typed('.animated-text', {
            strings: ['EXPLORE UNLIMITED STRENGTH', 'WITH ARTIFICIAL INTELLIGENCE'],
            typeSpeed: 50,
            backSpeed: 60,
            backDelay: 1000,
            loop: true,
          });
        }}
      />
    </>
  );
}
