import Head from "next/head";
import localFont from "next/font/local";
import { useEffect, useRef } from 'react';
// import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const videoRef = useRef(null);

  useEffect(() => {
    const video = videoRef.current;
    if (video) {
      video.play().catch(() => {
        // Handle autoplay rejection or errors
      });
    }
  }, []);
  <style jsx>{`
    /* Hide any media controls */
    video::-internal-media-controls {
      display: none !important;
    }

    video::-webkit-media-controls {
      display: none !important;
    }

    /* Disable interactions on the video */
    .background-video {
      pointer-events: none;
    }
      video::-internal-media-controls {
    display: none !important;
}

video::-webkit-media-controls {
    display: none !important;
}
.background-video {
  pointer-events: none;
}

  `}</style>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        
  {/* <video className="absolute inset-0 w-full h-full  object-cover "  autoPlay muted loop>
    <source src="/aivideo2.mp4" type="video/mp4" />
  </video> */}
  
  




  <video
        className="background-video pb-6"
        ref={videoRef}
        controls
        autoPlay
        muted
        loop
        playsInline
        preload="auto"
        src="https://videos.pexels.com/video-files/3129595/3129595-uhd_2560_1440_30fps.mp4"
      >
        
      </video>
  <div className="m-auto flex justify-center mb-28">
  <div class="content ">

    {/* <!-- Your content here --> */}
    <img src='Logo.gif' class="h-60 w-50 m-auto" />
    <h1 class="text-5xl font-bold text-center ">Shakktii AI</h1>
    <p class="mt-4 text-xl">EXPLORE UNLIMITED STRENGTH OF</p>
    <p class="mt-4 text-xl text-center">AI</p>
    
  </div></div>


</>
  );
}
